name: camoufox test
on: [push]
jobs:
  test_camoufox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install botright
      run: pip install botright
    - name: Install playwright
      run: playwright install
    - name: Run your tests
      run: xvfb-run python camoufoxtest.py -s -screen 0 1920x1080x16
