name: camoufox test
on: [push]
jobs:
  test_camoufox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install drissionpage
      run: pip install patchright
    - name: upgrade
      run: patchright install chromium
    - name: download chrome
      run: |
        curl https://github.com/adryfish/fingerprint-chromium/releases/download/131.0.6778.264/ungoogled-chromium_131.0.6778.264-1_linux.tar.xz --output ./ungoogled-chromium_131.0.6778.264-1_linux.tar.xz
      working-directory: ${{ github.workspace }}
    - name: Extract tgz
      uses: ihiroky/extract-action@v1
      with:
        file_path: './ungoogled-chromium_131.0.6778.264-1_linux.tar.xz'
        extract_dir: './'
    - name: run test
      run: xvfb-run python test.py
