name: camoufox test
on: [push]
jobs:
  test_camoufox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install drissionpage
      run: pip install DrissionPage
    - name: upgrade
      run: pip install DrissionPage --upgrade
    - name: creat dir
      run: |
        mkdir chrome
      working-directory: ${{ github.workspace }}
    - name: download chrome
      run: |
        curl https://github.com/adryfish/fingerprint-chromium/releases/download/130.0.6723.116/ungoogled-chromium_130.0.6723.116-1_linux.tar.xz --output ./chrome/ungoogled-chromium_130.0.6723.116-1_linux.tar.xz
      working-directory: ${{ github.workspace }}
    - name: Extract tgz
      uses: ihiroky/extract-action@v1
      with:
        file_path: './chrome/ungoogled-chromium_130.0.6723.116-1_linux.tar.xz'
        extract_dir: './chrome'
    - name: run test
      run: xvfb-run python test.py
